---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: demo-secret
  namespace: default
spec:
  encryptedData:
    password: AgC39tGkHgVJbqR85WMlT/vPdXNOsH/ZVHLIot+UUyDSBrh67IjQ7mW8OHnfa96131QBl9aLgH8k+zAT7DZ+IS8loeljMF2Tp8mU0a5CNDAYZHl9UwrSRHgD/PH9O9gv/RKVKgNvhsiwzNYWaPYzj/UOzsAH5ARlLN8Y3FsGytaSmEkOczZzT0uoOgJtiSq7wYrW8TKa07rryhQR22CxkkR0jiRl+/ADrFzKsWPleN37c/QNOW0yOtrFqZo0Gd4L8hYAYEKPIkXZWdzRET4YSEi3/qQPGfb3BiNGvcPart+9m+0uThBLQLnnZn3VrTrFIuROVnK5Fiw6/kNLN5SPzvDNTcRXqvHVn+GluRwYZZK4eITrOLxHRZ0vU1/6C5OzNKDKWczu47m2a5gHLRjZ7wiwlGRvgI4469VDWD2Gl9sUEIozoTsGxnVbLMD6b8EVBpWYl8tme1E3dd2yWKfmazV3VHasQF7NOBZZbSrxTgg2ChMNJy/D2eWjhuXBIvuFdEqKPiMnGsYWpANHBF/4YVvwp2gDXERncV4abU479Rdap/Lh+OGOBc/FSNykKDa6bIFNLFiUc2MvpJql8TJICsWJi1qcz4Sz+F3XAQ3NOfYcVLSTsF/LhxscFIOi6OGcM6Zhg46wcarjwRoT2Ra1fxt2lKn4fg4wfiWwfVqCQl2pQm8/rUAw1cDEvkw8p5VnRIiET2cBuXAZIG9KvisR
  template:
    metadata:
      creationTimestamp: null
      name: demo-secret
      namespace: default
