---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: demo-secret
  namespace: default
spec:
  encryptedData:
    password: AgC0DjVMYuNn2S/qSiPIxZ8XxGrGmQ9FA+vKD+59KcZmR+CIpULdPM0++gRFNaufRafdQR65iIcPztUtDi9ACihToR45Q2/B6AMF4RF5GfOQ0GxmNrUbVNzoGA84IxBMN19GwqtOjk2RITjxMD6xvrELC1xUv7M+WioLiDWKJ003E5A8lCQ/f15791xYddgFIZpE8IvNnetUpm904DLLiKFYcekaAkIdqOjS5vGXkhRYWQEAblb7X85JlfIj4LLSY+Q/giHNAJhaAnTz6VcRrlX17NxqRKCzAWLXnIQwLwBWIijGynXbZFsWtxueZ6pICztGcrYz2i1bAZOIAr8bfcq7JbsfjUsnOZIZeux5yu8WUU3T/801f8jMyaKLBbTD2jdgGeu9xMKAOCshb2rQjhPTT2+8gbHyeO3M9eJPPXnLvzl/ZBsEBhlcoX/fuDfEaL0kmUbmU4HBIdszCti304iB+A1YqoMBQx47UfHvqj3rzdcJN8V8NK8eebkj/OYAc3Ea+BrqTyMBd4I0+gRvLwrWRBGg7Nd7sDI7Lw5H1IzPoB/rC0fDfA/GWnrHZvHjAcnFUqYZr4O337s9TEYLkbAfmsjcuRrcHzHhm7yA0t0nRf5X2YeVj5MYS0WZ/l0LW+K+XqPkNVKujlSppN8Srslr17xXdbfwWADx5HgIyJThT5ZFPMCY76qyrjvpEq875QE9GoDIQUt2fg==
  template:
    metadata:
      creationTimestamp: null
      name: demo-secret
      namespace: default
    type: Opaque
